// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestNavigateur {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {

        vars = new Dictionary<string, object>();
    }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]

  public void VerifFirefox()
    {
        driver = new FirefoxDriver();
        js = (IJavaScriptExecutor)driver;
        PremiereVerif();
    }

  [Test]

  public void VerifChrome()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        //PremiereVerif();
    }
  private void PremiereVerif() {
    // Test name: Untitled
    // Step # | name | target | value
    // 1 | open | /index.jsp | 
    driver.Navigate().GoToUrl("http://192.168.18.104/index.jsp");
    // 2 | assertText | css=h2 | Bienvenue sur votre Banque en ligne !!!
    Assert.That(driver.FindElement(By.CssSelector("h2")).Text, Is.EqualTo("Bienvenue sur votre Banque en ligne !!!"));
    // 3 | click | linkText=VBEL | 
    driver.FindElement(By.LinkText("VBEL")).Click();
    // 4 | click | linkText=VBEL | 
    driver.FindElement(By.LinkText("VBEL")).Click();
    // 5 | click | css=.navbar | 
    driver.FindElement(By.CssSelector(".navbar")).Click();
    // 6 | click | linkText=Accès client | 
    driver.FindElement(By.LinkText("Accès client")).Click();
    // 7 | click | id=authIdentifiant | 
    driver.FindElement(By.Id("authIdentifiant")).Click();
    // 8 | assertElementPresent | id=authIdentifiant | 
    var elements = driver.FindElements(By.Id("authIdentifiant"));
    Assert.True(elements.Count > 0);
    // 9 | click | css=html | 
    driver.FindElement(By.CssSelector("html")).Click();
    // 10 | click | id=authMotdepasse | 
    driver.FindElement(By.Id("authMotdepasse")).Click();
    // 11 | click | id=authMotdepasse | 
    driver.FindElement(By.Id("authMotdepasse")).Click();
    // 12 | doubleClick | id=authMotdepasse | 
    {
      var element = driver.FindElement(By.Id("authMotdepasse"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    // 13 | assertElementPresent | id=authMotdepasse | 
    var elements2 = driver.FindElements(By.Id("authMotdepasse"));
    Assert.True(elements2.Count > 0);
    // 14 | close |  | 
    driver.Close();
  }
}
